on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # clone source code
      - name: Checkout
        uses: actions/checkout@v3

      # registry login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.srcmesh.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build and push image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: python-app
          push: true
          tags: registry.srcmesh.dev/workshop/aaaa:0.0.1

  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}